apiVersion: v1
kind: ReplicationController
metadata:
  name: database
  labels:
    name: database
spec:
  replicas: 1
  selector:
    name: database
  template:
    metadata:
      labels:
        name: database
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: labmanpassword
            - name: POSTGRES_USER
              value: labman
            - name: POSTGRES_DB
              value: labman_db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
